//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRM.Entities {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textes() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRM.Entities.Textes", typeof(Textes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accélération.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moy..
        /// </summary>
        public static string AverageLap {
            get {
                return ResourceManager.GetString("AverageLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toutes les équipes sont aux stands pour sélectionner le type de pneus et/ou le pilote. .
        /// </summary>
        public static string BeforeStartRaceConsign1 {
            get {
                return ResourceManager.GetString("BeforeStartRaceConsign1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyer sur le bouton &quot;Brake&quot; pour changer l&apos;action à exécuter, appuyer sur le bouton &quot;Lane Change&quot; pour valider une action. .
        /// </summary>
        public static string BeforeStartRaceConsign2 {
            get {
                return ResourceManager.GetString("BeforeStartRaceConsign2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Best..
        /// </summary>
        public static string BestLap {
            get {
                return ResourceManager.GetString("BestLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les deux.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frein.
        /// </summary>
        public static string Brake {
            get {
                return ResourceManager.GetString("Brake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frein + gaz à 0.
        /// </summary>
        public static string BrakeAndZeorGaz {
            get {
                return ResourceManager.GetString("BrakeAndZeorGaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat.
        /// </summary>
        public static string CarHealth {
            get {
                return ResourceManager.GetString("CarHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voitures.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courbe frein.
        /// </summary>
        public static string ChangeBrakeCurve {
            get {
                return ResourceManager.GetString("ChangeBrakeCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courbe acc..
        /// </summary>
        public static string ChangeThCurve {
            get {
                return ResourceManager.GetString("ChangeThCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer?.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consommation.
        /// </summary>
        public static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sur incident aléatoire.
        /// </summary>
        public static string DamagesRandom {
            get {
                return ResourceManager.GetString("DamagesRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incident aléatoire &amp; Track Call.
        /// </summary>
        public static string DamagesRandomAndTC {
            get {
                return ResourceManager.GetString("DamagesRandomAndTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sur Track Call.
        /// </summary>
        public static string DamagesTrackCall {
            get {
                return ResourceManager.GetString("DamagesTrackCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Défaut.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ma Piste.
        /// </summary>
        public static string DefaultTrack {
            get {
                return ResourceManager.GetString("DefaultTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désactivé.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disqualifié.
        /// </summary>
        public static string Disqualified {
            get {
                return ResourceManager.GetString("Disqualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disqualifier.
        /// </summary>
        public static string Disqualify {
            get {
                return ResourceManager.GetString("Disqualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ne rien faire.
        /// </summary>
        public static string DoNothing {
            get {
                return ResourceManager.GetString("DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frein dynamique.
        /// </summary>
        public static string DynamicBrake {
            get {
                return ResourceManager.GetString("DynamicBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activé.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tour à vitesse réduite.
        /// </summary>
        public static string EndLapWithPenalityPower {
            get {
                return ResourceManager.GetString("EndLapWithPenalityPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fin de relais.
        /// </summary>
        public static string EndOfRelay {
            get {
                return ResourceManager.GetString("EndOfRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fin de relais-Pénalité.
        /// </summary>
        public static string EndOfRelayPenality {
            get {
                return ResourceManager.GetString("EndOfRelayPenality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout le monde.
        /// </summary>
        public static string EndRaceType_AllFinish {
            get {
                return ResourceManager.GetString("EndRaceType_AllFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fin directe.
        /// </summary>
        public static string EndRaceType_FirstFinish {
            get {
                return ResourceManager.GetString("EndRaceType_FirstFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standard.
        /// </summary>
        public static string EndRaceType_Standard {
            get {
                return ResourceManager.GetString("EndRaceType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ENDURANCE.
        /// </summary>
        public static string Endurance {
            get {
                return ResourceManager.GetString("Endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Course d&apos;endurance avec limite de temps au choix.
        /// </summary>
        public static string EnduranceSubTitle {
            get {
                return ResourceManager.GetString("EnduranceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Premier.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Premier tour.
        /// </summary>
        public static string FirstLap {
            get {
                return ResourceManager.GetString("FirstLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fréquent.
        /// </summary>
        public static string Frequent {
            get {
                return ResourceManager.GetString("Frequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carb..
        /// </summary>
        public static string FuelShort {
            get {
                return ResourceManager.GetString("FuelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Général.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GRAND PRIX.
        /// </summary>
        public static string GrandPrix {
            get {
                return ResourceManager.GetString("GrandPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Course de type Grand Prix avec nombre de tours au choix.
        /// </summary>
        public static string GrandPrixSubTitle {
            get {
                return ResourceManager.GetString("GrandPrixSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drapeau vert.
        /// </summary>
        public static string GreenFlag {
            get {
                return ResourceManager.GetString("GreenFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à heure(s).
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incident.
        /// </summary>
        public static string Incident {
            get {
                return ResourceManager.GetString("Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tour.
        /// </summary>
        public static string Lap {
            get {
                return ResourceManager.GetString("Lap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rec..
        /// </summary>
        public static string LapRecord {
            get {
                return ResourceManager.GetString("LapRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Laps.
        /// </summary>
        public static string Laps {
            get {
                return ResourceManager.GetString("Laps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LAST.
        /// </summary>
        public static string LastLap {
            get {
                return ResourceManager.GetString("LastLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ch. voie.
        /// </summary>
        public static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ch. voie +Frein.
        /// </summary>
        public static string LCAndBrake {
            get {
                return ResourceManager.GetString("LCAndBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ch. voie +Frein + Gaz 0.
        /// </summary>
        public static string LCAndBrakeAndZGaz {
            get {
                return ResourceManager.GetString("LCAndBrakeAndZGaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obligatoire.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tours maximum.
        /// </summary>
        public static string MaxLaps {
            get {
                return ResourceManager.GetString("MaxLaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Puissance max.
        /// </summary>
        public static string MaxPower {
            get {
                return ResourceManager.GetString("MaxPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à équipes maximum.
        /// </summary>
        public static string MaxTeams {
            get {
                return ResourceManager.GetString("MaxTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyer sur le bouton start du gamepad de l&apos;équipe.
        /// </summary>
        public static string Mess_PressStartOnTeamGamePad {
            get {
                return ResourceManager.GetString("Mess_PressStartOnTeamGamePad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de trouver votre base SSD utilisez la page de configuration pour connecter votre base.
        /// </summary>
        public static string Message_NoPB {
            get {
                return ResourceManager.GetString("Message_NoPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de démarrer la course tant que tous les pilotes n&apos;ont pas terminé leur choix de pneus et / ou de pilote.
        /// </summary>
        public static string MessageCantStartRace {
            get {
                return ResourceManager.GetString("MessageCantStartRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer la suppression ?.
        /// </summary>
        public static string MessageConfirmDelete {
            get {
                return ResourceManager.GetString("MessageConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous allez supprimer le véhicule {0}. Continuer ?.
        /// </summary>
        public static string MessageConfirmDeleteCar {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention, confirmez vous la programmation de l&apos;ID pour la voiture en piste. Une seule voiture doit être en piste..
        /// </summary>
        public static string MessageConfirmProgCarId {
            get {
                return ResourceManager.GetString("MessageConfirmProgCarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voules vous linéariser la courbe entre {0} et {1} ?.
        /// </summary>
        public static string MessageLinearize {
            get {
                return ResourceManager.GetString("MessageLinearize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer l&apos;arrêt de la course ?.
        /// </summary>
        public static string MessConfirmStopRace {
            get {
                return ResourceManager.GetString("MessConfirmStopRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moyen.
        /// </summary>
        public static string Moyen {
            get {
                return ResourceManager.GetString("Moyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un nouveau pilote.
        /// </summary>
        public static string NewPilote {
            get {
                return ResourceManager.GetString("NewPilote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pilote.
        /// </summary>
        public static string Pilot {
            get {
                return ResourceManager.GetString("Pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pilotes.
        /// </summary>
        public static string Pilots {
            get {
                return ResourceManager.GetString("Pilots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PitPro.
        /// </summary>
        public static string PitPro {
            get {
                return ResourceManager.GetString("PitPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pneus ?.
        /// </summary>
        public static string PitStopChangeTires {
            get {
                return ResourceManager.GetString("PitStopChangeTires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer ?.
        /// </summary>
        public static string PitStopEnd {
            get {
                return ResourceManager.GetString("PitStopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pilote ?.
        /// </summary>
        public static string PitStopSelectPilot {
            get {
                return ResourceManager.GetString("PitStopSelectPilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ENTRAINEMENT.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aux stands.
        /// </summary>
        public static string PrepareToRace {
            get {
                return ResourceManager.GetString("PrepareToRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qualification.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Course.
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Course terminée !.
        /// </summary>
        public static string RaceFinished {
            get {
                return ResourceManager.GetString("RaceFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres de course.
        /// </summary>
        public static string RaceParams {
            get {
                return ResourceManager.GetString("RaceParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courses.
        /// </summary>
        public static string Races {
            get {
                return ResourceManager.GetString("Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RallyCross.
        /// </summary>
        public static string RallyCross {
            get {
                return ResourceManager.GetString("RallyCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rare.
        /// </summary>
        public static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carburant.
        /// </summary>
        public static string Refuel {
            get {
                return ResourceManager.GetString("Refuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réparation.
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résistance.
        /// </summary>
        public static string Resistance {
            get {
                return ResourceManager.GetString("Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection d&apos;un pilote existant.
        /// </summary>
        public static string SelectPilot {
            get {
                return ResourceManager.GetString("SelectPilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SmartSensor.
        /// </summary>
        public static string SmartSensor {
            get {
                return ResourceManager.GetString("SmartSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Atténuation frein.
        /// </summary>
        public static string SoftBrake {
            get {
                return ResourceManager.GetString("SoftBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Course contre la montre en solo.
        /// </summary>
        public static string SoloSubTitle {
            get {
                return ResourceManager.GetString("SoloSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish !.
        /// </summary>
        public static string TeamFinished {
            get {
                return ResourceManager.GetString("TeamFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equipes.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TIMEATTACK.
        /// </summary>
        public static string TimeAttack {
            get {
                return ResourceManager.GetString("TimeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes maximum.
        /// </summary>
        public static string TimeLimit {
            get {
                return ResourceManager.GetString("TimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pneus.
        /// </summary>
        public static string Tires {
            get {
                return ResourceManager.GetString("Tires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration pneus.
        /// </summary>
        public static string TiresConfig {
            get {
                return ResourceManager.GetString("TiresConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur à saisir permet de limiter la capacité d&apos;accélération. Pour comparaison une valeur de 20 correspond à une accélération maximale..
        /// </summary>
        public static string TiresConsigne_Acceleration {
            get {
                return ResourceManager.GetString("TiresConsigne_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur à saisir permet d&apos;ajouter un délai en millisecondes avant prise en compte du freinage..
        /// </summary>
        public static string TiresConsigne_BrakeDelai {
            get {
                return ResourceManager.GetString("TiresConsigne_BrakeDelai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur à saisir permet de spécifier le pourcentage d&apos;usure par rapport à l&apos;usure normale.
        /// </summary>
        public static string TiresConsigne_Wear {
            get {
                return ResourceManager.GetString("TiresConsigne_Wear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TOURNOI.
        /// </summary>
        public static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tournoi multi joueur avec courses de type grand prix.
        /// </summary>
        public static string TournamentSubTitle {
            get {
                return ResourceManager.GetString("TournamentSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track call.
        /// </summary>
        public static string TrackCall {
            get {
                return ResourceManager.GetString("TrackCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pistes.
        /// </summary>
        public static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trés fréquent.
        /// </summary>
        public static string TresFrequent {
            get {
                return ResourceManager.GetString("TresFrequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Très rare.
        /// </summary>
        public static string TresRare {
            get {
                return ResourceManager.GetString("TresRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version d&apos;évaluation :.
        /// </summary>
        public static string TrialVersion {
            get {
                return ResourceManager.GetString("TrialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vibrations gachettes.
        /// </summary>
        public static string TriggerVibrations {
            get {
                return ResourceManager.GetString("TriggerVibrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carburant.
        /// </summary>
        public static string UsedFuel {
            get {
                return ResourceManager.GetString("UsedFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réparations.
        /// </summary>
        public static string UsedHealth {
            get {
                return ResourceManager.GetString("UsedHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pneus.
        /// </summary>
        public static string UsedTires {
            get {
                return ResourceManager.GetString("UsedTires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vibrations.
        /// </summary>
        public static string Vibrations {
            get {
                return ResourceManager.GetString("Vibrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attente de PitStop.
        /// </summary>
        public static string WaitForPitStop {
            get {
                return ResourceManager.GetString("WaitForPitStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drapeau jaune.
        /// </summary>
        public static string YellowFlag {
            get {
                return ResourceManager.GetString("YellowFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
