#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ESRM.Mobile.Droid.Resource", IsApplication=true)]

namespace ESRM.Mobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int max = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public const int numberProgressBarStyle = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int progress = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int progress_reached_bar_height = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int progress_reached_color = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int progress_text_color = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int progress_text_offset = 2130771976;
			
			// aapt resource value: 0x7f010006
			public const int progress_text_size = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int progress_text_visibility = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int progress_unreached_bar_height = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int progress_unreached_color = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back11 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back5 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back6 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back7 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back8 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int back9 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int border1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int border2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int BrakeIncident = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int covered = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int empty = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int EngineIncident = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Finish = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Hard = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Intermediate = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Medium = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int NightClear = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int NightClear1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int NightRain1 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int PitStop = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int rain = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int red_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int repair = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Soft = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int stormy = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int StormyRain3t = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int sunny = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int SunnyAndRainRisk1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int SunnyAndRainRisk2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int SunnyAndRainRisk3 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int SunnyCloudy1 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int SunnyCloudy2 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int SuspensionIncident = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int thinning = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int TiresIncident = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Wet = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int yellowFlag = 2130837541;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int GridLayoutCurvesInfos = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int bestlap = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int brakecurvetitle = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int brakecurvetitletext = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int btnConnect = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int btnsettings = 2131165189;
			
			// aapt resource value: 0x7f07001b
			public const int driverpower = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int fuelBar = 2131165207;
			
			// aapt resource value: 0x7f07000a
			public const int gap = 2131165194;
			
			// aapt resource value: 0x7f070026
			public const int gridLayoutActions = 2131165222;
			
			// aapt resource value: 0x7f070016
			public const int gridLayoutCarInfos = 2131165206;
			
			// aapt resource value: 0x7f070007
			public const int gridLayoutHeader = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int gridLayoutHeader2 = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int gridLayoutHeader3 = 2131165205;
			
			// aapt resource value: 0x7f07001d
			public const int gridLayoutTires = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int gridLayoutWeather = 2131165217;
			
			// aapt resource value: 0x7f070019
			public const int healthBar = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int healthpower = 2131165212;
			
			// aapt resource value: 0x7f070012
			public const int incarpro = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int invisible = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int lapcount = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int lastlap = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int listView1 = 2131165190;
			
			// aapt resource value: 0x7f070020
			public const int mandatoryPS = 2131165216;
			
			// aapt resource value: 0x7f070008
			public const int position = 2131165192;
			
			// aapt resource value: 0x7f07002a
			public const int radioButton1 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int radioButton2 = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int radioButton3 = 2131165228;
			
			// aapt resource value: 0x7f070029
			public const int radioGroup1 = 2131165225;
			
			// aapt resource value: 0x7f07002d
			public const int select_server = 2131165229;
			
			// aapt resource value: 0x7f070003
			public const int serverip = 2131165187;
			
			// aapt resource value: 0x7f07002e
			public const int settings = 2131165230;
			
			// aapt resource value: 0x7f070027
			public const int spinnerTeams = 2131165223;
			
			// aapt resource value: 0x7f07000b
			public const int stateImage = 2131165195;
			
			// aapt resource value: 0x7f070028
			public const int team = 2131165224;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f07001a
			public const int textView2 = 2131165210;
			
			// aapt resource value: 0x7f070013
			public const int thcurvetitle = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int thcurvetitletext = 2131165200;
			
			// aapt resource value: 0x7f07001e
			public const int tireTypeImpg = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int tireTypeText = 2131165215;
			
			// aapt resource value: 0x7f070018
			public const int tiresBar = 2131165208;
			
			// aapt resource value: 0x7f070001
			public const int visible = 2131165185;
			
			// aapt resource value: 0x7f070025
			public const int weatherForecastText = 2131165221;
			
			// aapt resource value: 0x7f070022
			public const int weatherImg = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int weatherNextImg = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int weatherText = 2131165220;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RaceDatas = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int mainmenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int Settings = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int TeamSelect = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int select_server = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int NumberProgressBar_Beauty_Red = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int NumberProgressBar_Default = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int NumberProgressBar_Funny_Orange = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int NumberProgressBar_Grace_Yellow = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int NumberProgressBar_Passing_Green = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int NumberProgressBar_Relax_Blue = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int NumberProgressBar_Twinkle_Night = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int NumberProgressBar_Warning_Red = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Theme_NoTitle = 2131034120;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] NumberProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public const int NumberProgressBar_max = 1;
			
			// aapt resource value: 0
			public const int NumberProgressBar_progress = 0;
			
			// aapt resource value: 4
			public const int NumberProgressBar_progress_reached_bar_height = 4;
			
			// aapt resource value: 3
			public const int NumberProgressBar_progress_reached_color = 3;
			
			// aapt resource value: 7
			public const int NumberProgressBar_progress_text_color = 7;
			
			// aapt resource value: 8
			public const int NumberProgressBar_progress_text_offset = 8;
			
			// aapt resource value: 6
			public const int NumberProgressBar_progress_text_size = 6;
			
			// aapt resource value: 9
			public const int NumberProgressBar_progress_text_visibility = 9;
			
			// aapt resource value: 5
			public const int NumberProgressBar_progress_unreached_bar_height = 5;
			
			// aapt resource value: 2
			public const int NumberProgressBar_progress_unreached_color = 2;
			
			public static int[] Themes = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int Themes_numberProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
